# -*- coding: utf-8 -*-
"""Q1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eSlJwiQ_aoinKA5k-WgzVgXLJFs3gRBu
"""

import pandas as pd
import numpy as np

def tuple_count(z):
  p = []
  for each in z:
    q = z.count(each)
    p.append(q)
  return p


z = [(5,8),(6,9),(3,5),(5,8),(3,5),(5,8)]
print(tuple_count(z))