# -*- coding: utf-8 -*-
"""Q4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k3hbNglybr8HEA1eZVoLk7Z9BbrFbOb_
"""

import numpy as np
import pandas as pd

def Sort_Tuple(listA):
  listA.sort(key = lambda x: x[0])
  return listA
listA=[(1,2), (4,3), (2,10), (12, 5), (6, 7), (9,11), (15, 4)]
print(Sort_Tuple(listA))

def Sort_Tuple(listA):
  listA.sort(key = lambda x: x[1])
  return listA
listA=[(1,2), (4,3), (2,10), (12, 5), (6, 7), (9,11), (15, 4)]
print(Sort_Tuple(listA))

def Sort_Tuple(listA):
  listA.sort(key = lambda x: x[0],reverse=True)
  return listA
listA=[(1,2), (4,3), (2,10), (12, 5), (6, 7), (9,11), (15, 4)]
print(Sort_Tuple(listA))

def Sort_Tuple(listA):
  listA.sort(key = lambda x: x[1],reverse=True)
  return listA
listA=[(1,2), (4,3), (2,10), (12, 5), (6, 7), (9,11), (15, 4)]
print(Sort_Tuple(listA))