# -*- coding: utf-8 -*-
"""Q5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fRFy6nXn2-YDBPz5FSCd_-p7Jksq7rfc
"""

print("A mutable object can be changed after it is created, and an immutable object can't."
"Objects of built-in types like (int, float, bool, str, tuple, unicode) are immutable."
"Objects of built-in types like (list, set, dict) are mutable.")