# -*- coding: utf-8 -*-
"""Q6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rxLGzsXG5kMK-B1N5P4fiPwyEBjgD7zi
"""

import pandas as pd 
import numpy as np

from google.colab import files
df=files.upload()

df=pd.read_csv("banking.csv")

df.head()

df1=df["education"]

df2=df1.unique()

df2

df3=df["y"]

df3.value_counts()

df.mean()

df.isnull().sum()

df.info()

#mean age of every marital status 
married=df[df.marital=="married"].age.mean()
print("married avg age=",married)

unmarried=df[df.marital=="single"].age.mean()
print("unmarried avg age=",unmarried)

divorced=df[df.marital=="divorced"].age.mean()
print("divorced avg age=",divorced)

unknown=df[df.marital=="unknown"].age.mean()
print("unknown avg age=",unknown)